### ISSUE TITLE
Get key/password from Android doesn't strongly match

### ISSUE THREAD

**Issue by michaeldimoudis** [has-taiar/KeyChain.Net#5]
Hi

So the get key/password value method Android implementation does not choose a strong match. It doesn't do an Equals it does a Contains. I had 2 keys, Token and RefreshToken, whenever I wanted to get the Token it was giving me the RefreshToken. I got around this by simply renaming the keys to Token and Refresh.

I don't have time to create a fix and pull request yet, but thought I'd let anyone else know if they have encountered this.

**Comment by dot-ly** [comment]
thanks for this! Where are you storing your Keystore password? why does Android insist on a Password.
